<a href="https://colab.research.google.com/github/LIMSONA/30min_summary_study/blob/main/2_NUMPY_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

## 기초

In [ ]:
import numpy as np
data = [[1,2,3],[4,5,6],[7,8,9]]

a=np.array(data)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a.dtype #형태 확인

dtype('int64')

In [ ]:
data_2=[[1,2.0,3.0],[4,5,6]] #하나를 소수로 바꿔주면
b=np.array(data_2)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
b.dtype

dtype('float64')

### 형 변환하기

* np.astype( )

In [ ]:
#형변환 .astype( )
a = a . astype(np.float32)  #동일식 a = a . astype('float32')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [ ]:
a[0][1]

2.0

In [ ]:
a[0]

array([1., 2., 3.], dtype=float32)

### 배열


* np.arange(start, stop, step) : step에 따라 증가하는 수열을 생성한다.
* reshape : 만들어진 배열의 데이터를 그대로 가지고 형태를 바꿔준다.

In [ ]:
#.arange만들기 .arrange (시작, 끝, 스텝)
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
#형태 만들기 reshape( )
#-> 갯수 꼭 맞춰서 reshape 하기!
np.arange(1,10).reshape(3,3)  

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,13).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

### 결측값

* np.nan
- 자료형 Float형일대만 사용가능 
- 자료형 Int에서는 오류가 발생한다.
- 배열에서 연산할 경우 오류가 발생하지 않지만, 결과값이 NaN이 된다.

In [ ]:
#결측값 
np.nan *10

nan

In [ ]:
a[0][1]=np.nan
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [ ]:
c= np.arange(1,10).reshape(3,3)  
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
c[0][1]=np.nan    #int형이여서 오류가 뜸

ValueError: ignored

### 값 입력

* np.linspace( 시작, 끝, 몇 개를 생성할지)

In [ ]:
a=np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## 연산

* 반복문을 사용하지 않아도,  배열의 모든 원소는 반복연산이 사용된다.
*  선형 대수 식을 사용하여 연산 가능하다.


### 사칙연산

In [ ]:
data=np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 각 원소 더하기
data + data 

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
##파이썬과 비교!!
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [ ]:
# 각 원소 뺴기
data - data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# 각 원소 곱하기
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
# 각 원소 나누기 
data / data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

###행렬의 곱하기 하고 싶으면!

* 행렬 곱 구하는 연산 방법2가지
  1. np.dot( )
  2. @

  * 행렬 곱하는 방법 : 말그대로 행과 열의 곱하기
    * 1행*1열(첫번째x첫번째 + 두번째x두번째+.......) 
    * 2행*2열(첫번째x첫번째 + .........)
    * ............

In [ ]:
data=np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.dot(data,data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
data @ data

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

## 차원

*  대괄호의 개수로 차원을 파악
* .shape( ) 행렬의 차원을 출력
* .ndim( ) 차원을 출력 2D,3D 

### 0차원 : Scalar (하나의 데이터 값으로만 존재하는 것)

In [ ]:
a=np.array(1)
a

array(1)

In [ ]:
a.shape #행렬의 차원

()

In [ ]:
a.ndim #차원

0

###1차원 : Vector (숫자들의 배열 (1D array))

In [ ]:
#예시1
a=np.array([1])
a

array([1])

In [ ]:
a.shape 

(1,)

In [ ]:
a.ndim

1

In [ ]:
#예시2
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [ ]:
b.shape

(5,)

In [ ]:
b.ndim

1

### 2차원 : Matrix (숫자들의 2D array (rows: 행, columns: 열))

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape #2열 3행

(2, 3)

In [ ]:
a.ndim

2

### 3차원 이상 : Tensor (숫자들의 다차원 배열)

In [ ]:
a = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
a.shape

(2, 3, 2)

In [ ]:
a.ndim

3

## matrix 유형

In [ ]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

### zeros : 0으로 초기화된 배열 생성

In [ ]:
import numpy as np
c= np.zeros(12).reshape(2,3,2)
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
#동일한 식
e=np.zeros([2,3,2])
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
if c.all()==e.all(): 
  print('True')

True


In [ ]:
np.array_equal(c,e)

True

### ones  : 1로 초기화 된 배열 생성

In [ ]:
b = np.ones(12).reshape(2, 3, 2)
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### 단위 행렬 np.eye( ) 

* 주대각선의 원소가 모두 1이고 나머지 원소는 0인 정사각행렬 (단위행렬)

단위 행렬은 n차 정사각행렬 중에서 왼쪽 위에서 오른쪽 아래로의 대각선(↘) 위의 성분이 모두 1, 

그 이외의 성분은 모두 0인 행렬을 n차 단위행렬이라고 하고,
기호로 E 또는 I로 나타낸다.

In [ ]:
d= np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### empty : 초기화 하지 않고 배열만 생성, 기존에 메모리에 저장되어 있는 값으로 나타남

In [ ]:
f= np.empty([2, 3])
f

array([[1., 2., 3.],
       [4., 5., 6.]])

### full : 지정한 숫자로 초기화

* np.full((행,열), 채울 숫자)

In [ ]:
g = np.full((3,4),1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

### linspace(start, end(포함), number, endpoint = ) : 선형 구간을 지정한 개수만큼 분할한다.

 * np.linspace( 시작, 끝, 몇 개를 생성할지)
  - 시작과 끝은 포함한다
  * endpoint = True or False : 마지막 값을 포함시킬지 시키지 않을지 선택

In [ ]:
h= np.linspace(2,10,6)
h

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

##집계함수

- mean : 평균을 구하는 함수
- median : 데이터를 크기로 정렬하고 그 중 가운데 수 출력하는 함수
    
    ※ 만약 데이터 개수가 짝수일 경우 가장 가운데의 두 수의 평균을 구한다.
    
- var : 분산 구하는 함수
- std : 표준편차 구하는 함수
- sum : 합계 구하는 함수
- max : 가장 큰 수를 구하는 함수
- min : 가장 작은 수를 구하는 함수

In [ ]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a[0][0]= 100 # 동일한 식: a[0,1]= 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [ ]:
a[0,1]= 1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [ ]:
np.mean(a) #평균

114.4

In [ ]:
np.median(a) #중간값

6.5

In [ ]:
np.std(a) #표준편차

296.5485457728633

In [ ]:
np.var(a) #분산

87941.04

In [ ]:
np.sum(a) #합계

1144

In [ ]:
sum(a)  #비교!!!! 행과 행끼리 더해짐

array([ 105, 1006,    9,   11,   13])

In [ ]:
np.sum(a,axis=0)

array([ 105, 1006,    9,   11,   13])

In [ ]:
np.sum(a, axis=0)

In [ ]:
np.sum(a, axis=1)

In [ ]:
np.max(a)

In [ ]:
np.min(a)

# **PANDAS**

In [8]:
import numpy as np
import pandas as pd

## Series

In [26]:
data=np.arange(0,50,10)
data

array([ 0, 10, 20, 30, 40])

In [27]:
a = pd.Series(data, index=['a', 'b', 'c', 'd', 'e'])
print(a)

a     0
b    10
c    20
d    30
e    40
dtype: int64


In [28]:
b=pd.Series(data)
print(b)

0     0
1    10
2    20
3    30
4    40
dtype: int64


In [29]:
a['b']

10

In [31]:
a.loc['b'] #location 명시적으로 지정한 것이 나옴

10

In [33]:
a.iloc[1] #index location

10

### 산술연산

In [36]:
a

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [34]:
a+10

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [35]:
a-10

a   -10
b     0
c    10
d    20
e    30
dtype: int64

In [37]:
a*10

a      0
b    100
c    200
d    300
e    400
dtype: int64

In [38]:
a/10 #실수형으로 나옴

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [39]:
a//10

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [40]:
a%3

a    0
b    1
c    2
d    0
e    1
dtype: int64

### 비교연산자


In [41]:
a>15

a    False
b    False
c     True
d     True
e     True
dtype: bool

In [43]:
#어떤 값이 조건 만족하는지 보려면 boolean indexing사용한다
# '변수[ ]'로 한번더 묶어줌
a[a>15] 

c    20
d    30
e    40
dtype: int64

### 집계함수

- add : 더하기 함수
- sub : 빼기 함수
- mul : 곱하기 함수
- div : 나누기 함수
- mod : 나머지 구하는 함수
- min : 최소값 구하는 함수
- max  : 최대값 구하는 함수
- mean : 평균 구하는 함수
- median : 중앙값 구하는 함수
- std : 표준편차 구하는 함수
- var : 분산 구하는 함수

In [46]:
a.add(100) #동일 식: a+100

a    100
b    110
c    120
d    130
e    140
dtype: int64

In [45]:
a.sub(100) #동일 식: a-100

a   -100
b    -90
c    -80
d    -70
e    -60
dtype: int64

In [48]:
a.mul(100) #동일식 : a*100

a       0
b    1000
c    2000
d    3000
e    4000
dtype: int64

In [49]:
a.div(100) #동일식: a/100

a    0.0
b    0.1
c    0.2
d    0.3
e    0.4
dtype: float64

In [50]:
a.mod(100) #동일식: a%100

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [51]:
a.min()

0

In [52]:
a.max()

40

In [53]:
a.sum()

100

In [54]:
a.mean()

20.0

In [55]:
a.median()

20.0

In [56]:
a.std() #표준편차

15.811388300841896

In [57]:
a.var() #분산

250.0

## DataFrame

- 2차원 배열에 행과 열에 인덱스를 붙인 것이다.
- 가장 기본적인 데이터 구조이다.
- df['a']['b'] : df의 a열b행 

In [58]:
# randint니까 50이상 100이하 정수뽑아서, 4x3형태로 랜덤 생성
 
rawData = np.random.randint(50, 100, size=(4, 3)) 
rawData

array([[71, 52, 79],
       [94, 67, 76],
       [73, 59, 68],
       [75, 56, 91]])

In [129]:
df = pd.DataFrame(rawData,
                  index=['1반', '2반', '3반', '4반'], 
                  columns=['국', '영', '수'])
df

국   영   수
1반  71  52  79
2반  94  67  76
3반  73  59  68
4반  75  56  91

### 조회

In [77]:
df['국'] # 열 조회

1반    71
2반    94
3반    73
4반    75
Name: 국, dtype: int64

In [80]:
#비교!!!
df.loc['1반'] #행조회

국    71
영    52
수    79
Name: 1반, dtype: int64

In [81]:
df.iloc[0] #위와 동일값

국    71
영    52
수    79
Name: 1반, dtype: int64

### 평균, 추가, 삭제

In [130]:
#평균: round 반올림(소수점 2자리까지)

df['평균'] = round((df['국']+df['영']+df['수'])/3, 2)
df

국   영   수     평균
1반  71  52  79  67.33
2반  94  67  76  79.00
3반  73  59  68  66.67
4반  75  56  91  74.00

In [84]:
# 열('na') 추가하고 NaN값을 넣기
df['na']=np.nan
df

국   영   수     평균  na
1반  71  52  79  67.33 NaN
2반  94  67  76  79.00 NaN
3반  73  59  68  66.67 NaN
4반  75  56  91  74.00 NaN

In [85]:
# del 삭제
del df['na']
df

국   영   수     평균
1반  71  52  79  67.33
2반  94  67  76  79.00
3반  73  59  68  66.67
4반  75  56  91  74.00

In [86]:
df[df.평균>75]

국   영   수    평균
2반  94  67  76  79.0

In [108]:
# 삭제
df.drop(['평균'], axis=1)
df

국   영   수     평균
1반  71  52  79  67.33
2반  94  67  76  79.00
3반  73  59  68  66.67
4반  75  56  91  74.00

In [134]:
#위와 동일식
df=df.drop(['평균'],axis='columns')
df

국     영     수
1반  71.0  52.0  79.0
2반  94.0  67.0  76.0
3반  73.0  59.0   NaN
4반  75.0  56.0  91.0

### 결측값 처리

1. NaN
    - 자료형이 Float 실수형이어야 한다!
    - 배열에서 연산할 경우 오류가 발생하지 않지만  결과값이 NaN이 된다.
2. None 
    - 자료형이 None이다.
    - 배열 연산을 할 경우 오류가 발생한다.

 3.  처리방법 

- isnull() : 결측값 확인 (결측 이면  True , 결측이 아니면  False )
- notnull() : 결측값 확인 (결측 이면  False , 결측이 아니면  True )
- dropna() : 결측값 삭제
    - inplace = True : drop후 원본에 반영
- fillna(Num) : 결측값을 Num으로 채워 넣는다.

In [111]:
# 결측값이 실수여야하므로 형 확인하기
df.dtypes

국    int64
영    int64
수    int64
dtype: object

In [135]:
df=df.astype('float64')
df

국     영     수
1반  71.0  52.0  79.0
2반  94.0  67.0  76.0
3반  73.0  59.0   NaN
4반  75.0  56.0  91.0

In [136]:
df['수'][2]=np.nan
df

국     영     수
1반  71.0  52.0  79.0
2반  94.0  67.0  76.0
3반  73.0  59.0   NaN
4반  75.0  56.0  91.0

In [115]:
#결측값 삭제 .dropna( )

df.dropna(axis=0) 
#inplace=True는 변수지정하지 않아도 원본저장 
#행삭제는 axis=0

국     영     수
1반  71.0  52.0  79.0
2반  94.0  67.0  76.0
4반  75.0  56.0  91.0

In [122]:
df.dropna(axis=1) 

국     영
1반  71.0  52.0
2반  94.0  67.0
3반  73.0  59.0
4반  75.0  56.0

In [139]:
#결측값 채우기 .fillna( )

df.fillna('없다구용!')

국     영      수
1반  71.0  52.0     79
2반  94.0  67.0     76
3반  73.0  59.0  없다구용!
4반  75.0  56.0     91

### Multi-Index

- Index를 설정할 때 리스트의 리스트 형태로 넣어주면 다중 인덱스가 설정이 된다.

In [140]:
df

국     영     수
1반  71.0  52.0  79.0
2반  94.0  67.0  76.0
3반  73.0  59.0   NaN
4반  75.0  56.0  91.0

In [141]:
# index 와 columns을 바꿈
df.T

1반    2반    3반    4반
국  71.0  94.0  73.0  75.0
영  52.0  67.0  59.0  56.0
수  79.0  76.0   NaN  91.0

In [145]:
df

국     영     수
1반  71.0  52.0  79.0
2반  94.0  67.0  76.0
3반  73.0  59.0   NaN
4반  75.0  56.0  91.0

In [4]:
import pandas as pd
import numpy as np

In [8]:
rawData = np.random.randint(50, 100, size=(4, 3)) 

df=pd.DataFrame(rawData,index=['1반','2반','1반','2반'],
                columns=['국','영','수'])
df

국   영   수
1반  87  88  61
2반  86  80  82
1반  59  75  86
2반  59  98  91

In [9]:
#행 row 이중 인덱스 
# .index = [[ ]] 표현
df.index = [['1학년', '1학년', '2학년', '2학년'], ['1반', '2반', '1반', '2반']]
df

국   영   수
1학년 1반  87  88  61
    2반  86  80  82
2학년 1반  59  75  86
    2반  59  98  91

In [10]:
# 열 columns 이중 인덱스 
# .columns = [[ ]] 표현

df.columns = [['언어', '언어', '수리'],['국', '영', '수']]
df

언어      수리
         국   영   수
1학년 1반  87  88  61
    2반  86  80  82
2학년 1반  59  75  86
    2반  59  98  91

In [11]:
df['언어']

국   영
1학년 1반  87  88
    2반  86  80
2학년 1반  59  75
    2반  59  98

In [12]:
df['국']  #-> 오류발생

KeyError: ignored

In [13]:
df['언어']['국']

1학년  1반    87
     2반    86
2학년  1반    59
     2반    59
Name: 국, dtype: int64

In [14]:
df.iloc[0]

언어  국    87
    영    88
수리  수    61
Name: (1학년, 1반), dtype: int64

In [15]:
df.loc['1학년']

언어      수리
     국   영   수
1반  87  88  61
2반  86  80  82

In [16]:
df.loc['1학년'].loc['1반']

언어  국    87
    영    88
수리  수    61
Name: 1반, dtype: int64

### 데이터 사전분석

- info() : DataFrame을 구성하는 행과 열에 대한 정보를 나타내 주는 함수
- head(n) : DataFrame의 처음부터 n줄의 행을 출력
- tail(n) : DataFrame의 마지막 n줄의 행을 출력
- describe() : Series, DataFrame의 각 열에 대한 요약 통계
- dtypes : 데이터 자료형 확인

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('1학년', '1반') to ('2학년', '2반')
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   (언어, 국)  4 non-null      int64
 1   (언어, 영)  4 non-null      int64
 2   (수리, 수)  4 non-null      int64
dtypes: int64(3)
memory usage: 328.0+ bytes


In [19]:
df.head() #처음에 있는 것 5개

언어      수리
         국   영   수
1학년 1반  87  88  61
    2반  86  80  82
2학년 1반  59  75  86
    2반  59  98  91

In [20]:
df.tail() #마지막에 있는 것 5개 보여짐

언어      수리
         국   영   수
1학년 1반  87  88  61
    2반  86  80  82
2학년 1반  59  75  86
    2반  59  98  91

* **내가 예제 만들어보기**

In [29]:
sona=pd.DataFrame(np.arange(1,22).reshape(7,3))
sona

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15
5  16  17  18
6  19  20  21

In [31]:
sona.index=['해','달','별','꽃','풀','물','흙']
sona

0   1   2
해   1   2   3
달   4   5   6
별   7   8   9
꽃  10  11  12
풀  13  14  15
물  16  17  18
흙  19  20  21

In [32]:
sona.columns=['일','이','삼']
sona

일   이   삼
해   1   2   3
달   4   5   6
별   7   8   9
꽃  10  11  12
풀  13  14  15
물  16  17  18
흙  19  20  21

In [33]:
sona.head()

일   이   삼
해   1   2   3
달   4   5   6
별   7   8   9
꽃  10  11  12
풀  13  14  15

In [34]:
sona.tail()

일   이   삼
별   7   8   9
꽃  10  11  12
풀  13  14  15
물  16  17  18
흙  19  20  21

___

In [36]:
df.dtypes

언어  국    int64
    영    int64
수리  수    int64
dtype: object

In [38]:
df.describe() #통계함수

언어                    수리
              국          영          수
count   4.00000   4.000000   4.000000
mean   72.75000  85.250000  80.000000
std    15.88238  10.045729  13.190906
min    59.00000  75.000000  61.000000
25%    59.00000  78.750000  76.750000
50%    72.50000  84.000000  84.000000
75%    86.25000  90.500000  87.250000
max    87.00000  98.000000  91.000000

In [39]:
df.isnull()

언어            수리
            국      영      수
1학년 1반  False  False  False
    2반  False  False  False
2학년 1반  False  False  False
    2반  False  False  False

In [40]:
df.isnull().sum()

언어  국    0
    영    0
수리  수    0
dtype: int64

In [41]:
df.isnull().sum().sum()

0

In [48]:
#결측값 만들고 다시 검사하기

df=df.astype('float64')
df

언어          수리
           국     영     수
1학년 1반  87.0  88.0  61.0
    2반  86.0  80.0  82.0
2학년 1반  59.0  75.0  86.0
    2반  59.0  98.0  91.0

In [53]:
#멀티인덱스는 쉼표로 구분

df['수리','수']['1학년','1반']=np.nan
df

언어          수리
           국     영     수
1학년 1반  87.0  88.0   NaN
    2반  86.0  80.0  82.0
2학년 1반  59.0  75.0  86.0
    2반  59.0  98.0  91.0

In [54]:
df.isnull()

언어            수리
            국      영      수
1학년 1반  False  False   True
    2반  False  False  False
2학년 1반  False  False  False
    2반  False  False  False

In [55]:
df.isnull().sum()

언어  국    0
    영    0
수리  수    1
dtype: int64

In [56]:
df.isnull().sum().sum()

1

### 값의 연결

- concat : DataFrame끼리 결합
    - axis=0 or 1 : 아래로 데이터 연결 / 옆으로 데이터 연결
- append : 마지막 행에 데이터를 추가

※  concatenate : 배열끼리 결합

In [66]:
a=pd.DataFrame(np.arange(1,10).reshape(3,3))
a

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [59]:
b=pd.Series(np.arange(10,40,10))
b

0    10
1    20
2    30
dtype: int64

In [69]:
# 옆에 추가(열추가) axis=1
pd.concat([a,b],axis=1)

0  1  2   0
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [70]:
pd.concat([a,b],axis=1, ignore_index=True)
#ignore_index는 연속해서 index값 지정해준다

0  1  2   3
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [71]:
# 밑에 데이터 프레임으로서 추가(행추가) axis=0
pd.concat([a,b], axis=0, ignore_index=True)

0    1    2
0   1  2.0  3.0
1   4  5.0  6.0
2   7  8.0  9.0
3  10  NaN  NaN
4  20  NaN  NaN
5  30  NaN  NaN

In [72]:
#위의 식과 비교하기!!!
# 밑에 데이터 추가
a.append(b, ignore_index=True)

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  20  30