<a href="https://colab.research.google.com/github/LIMSONA/30min_summary_study/blob/main/2_NUMPY_PANDAS_VISUALIZATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

## 기초

In [2]:
import numpy as np
data = [[1,2,3],[4,5,6],[7,8,9]]

a=np.array(data)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
a.dtype #형태 확인

dtype('int64')

In [7]:
data_2=[[1,2.0,3.0],[4,5,6]] #하나를 소수로 바꿔주면
b=np.array(data_2)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [8]:
b.dtype

dtype('float64')

### 형 변환하기

* np.astype( )

In [13]:
#형변환 .astype( )
a = a . astype(np.float32)  #동일식 a = a . astype('float32')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [14]:
a[0][1]

2.0

In [15]:
a[0]

array([1., 2., 3.], dtype=float32)

### 배열


* np.arange(start, stop, step) : step에 따라 증가하는 수열을 생성한다.
* reshape : 만들어진 배열의 데이터를 그대로 가지고 형태를 바꿔준다.

In [18]:
#.arange만들기 .arrange (시작, 끝, 스텝)
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
#형태 만들기 reshape( )
#-> 갯수 꼭 맞춰서 reshape 하기!
np.arange(1,10).reshape(3,3)  

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.arange(1,13).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

### 결측값

* np.nan
- 자료형 Float형일대만 사용가능 
- 자료형 Int에서는 오류가 발생한다.
- 배열에서 연산할 경우 오류가 발생하지 않지만, 결과값이 NaN이 된다.

In [24]:
#결측값 
np.nan *10

nan

In [27]:
a[0][1]=np.nan
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [34]:
c= np.arange(1,10).reshape(3,3)  
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
c[0][1]=np.nan    #int형이여서 오류가 뜸

ValueError: ignored

### 값 입력

* np.linspace( 시작, 끝, 몇 개를 생성할지)

In [36]:
a=np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## 연산

* 반복문을 사용하지 않아도,  배열의 모든 원소는 반복연산이 사용된다.
*  선형 대수 식을 사용하여 연산 가능하다.


### 사칙연산

In [37]:
data=np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# 각 원소 더하기
data + data 

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [41]:
##파이썬과 비교!!
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [44]:
# 각 원소 뺴기
data - data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
# 각 원소 곱하기
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [43]:
# 각 원소 나누기 
data / data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

###행렬의 곱하기 하고 싶으면!

* 행렬 곱 구하는 연산 방법2가지
  1. np.dot( )
  2. @

  * 행렬 곱하는 방법 : 말그대로 행과 열의 곱하기
    * 1행*1열(첫번째x첫번째 + 두번째x두번째+.......) 
    * 2행*2열(첫번째x첫번째 + .........)
    * ............

In [48]:
data=np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.dot(data,data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [50]:
data @ data

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

## 차원

*  대괄호의 개수로 차원을 파악
* .shape( ) 행렬의 차원을 출력
* .ndim( ) 차원을 출력 2D,3D 

### 0차원 : Scalar (하나의 데이터 값으로만 존재하는 것)

In [51]:
a=np.array(1)
a

array(1)

In [54]:
a.shape #행렬의 차원

()

In [55]:
a.ndim #차원

0

###1차원 : Vector (숫자들의 배열 (1D array))

In [56]:
#예시1
a=np.array([1])
a

array([1])

In [58]:
a.shape 

(1,)

In [59]:
a.ndim

1

In [60]:
#예시2
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [61]:
b.shape

(5,)

In [62]:
b.ndim

1

### 2차원 : Matrix (숫자들의 2D array (rows: 행, columns: 열))

In [63]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
a.shape #2열 3행

(2, 3)

In [65]:
a.ndim

2

### 3차원 이상 : Tensor (숫자들의 다차원 배열)

In [66]:
a = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [67]:
a.shape

(2, 3, 2)

In [68]:
a.ndim

3

## matrix 유형

In [71]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

### zeros : 0으로 초기화된 배열 생성

In [76]:
c= np.zeros(12).reshape(2,3,2)
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [92]:
e=np.zeros([2,3,2])
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [85]:
if a.all()==e.all(): 
  print('True')

True


In [86]:
np.array_equal(a,e)

False

### ones  : 1로 초기화 된 배열 생성

In [73]:
b = np.ones(12).reshape(2, 3, 2)
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### 단위 행렬 np.eye( ) 

* 주대각선의 원소가 모두 1이고 나머지 원소는 0인 정사각행렬 (단위행렬)

단위 행렬은 n차 정사각행렬 중에서 왼쪽 위에서 오른쪽 아래로의 대각선(↘) 위의 성분이 모두 1, 

그 이외의 성분은 모두 0인 행렬을 n차 단위행렬이라고 하고,
기호로 E 또는 I로 나타낸다.

In [90]:
d= np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### empty : 초기화 하지 않고 배열만 생성, 기존에 메모리에 저장되어 있는 값으로 나타남

In [93]:
f= np.empty([2, 3])
f

array([[1., 2., 3.],
       [4., 5., 6.]])

### full : 지정한 숫자로 초기화

* np.full((행,열), 채울 숫자)

In [94]:
g = np.full((3,4),1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

### linspace(start, end(포함), number, endpoint = ) : 선형 구간을 지정한 개수만큼 분할한다.

 * np.linspace( 시작, 끝, 몇 개를 생성할지)
  - 시작과 끝은 포함한다
  * endpoint = True or False : 마지막 값을 포함시킬지 시키지 않을지 선택

In [97]:
h= np.linspace(2,10,6)
h

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

##집계함수

- mean : 평균을 구하는 함수
- median : 데이터를 크기로 정렬하고 그 중 가운데 수 출력하는 함수
    
    ※ 만약 데이터 개수가 짝수일 경우 가장 가운데의 두 수의 평균을 구한다.
    
- var : 분산 구하는 함수
- std : 표준편차 구하는 함수
- sum : 합계 구하는 함수
- max : 가장 큰 수를 구하는 함수
- min : 가장 작은 수를 구하는 함수

In [98]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
a[0][0]= 100 # 동일한 식: a[0,1]= 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [109]:
a[0,1]= 1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [110]:
np.mean(a) #평균

114.4

In [111]:
np.median(a) #중간값

6.5

In [112]:
np.std(a) #표준편차

296.5485457728633

In [113]:
np.var(a) #분산

87941.04

In [114]:
np.sum(a) #합계

1144

In [117]:
sum(a)  #비교!!!! 행과 행끼리 더해짐

array([ 105, 1006,    9,   11,   13])

In [119]:
np.sum(a,axis=0)

array([ 105, 1006,    9,   11,   13])

In [ ]:
np.sum