<a href="https://colab.research.google.com/github/LIMSONA/30min_summary_study/blob/main/2_PANDAS_NUMPY_VISUALIZATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
data = [[1,2,3],[4,5,6],[7,8,9]]

a=np.array(data)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
